---
abstract: 'Middleware to set default params for every request made by a spore client '
author:
  - Weborama
build_requires:
  JSON: 0
  Net::HTTP::Spore: 0
  Test::More: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-HTTP-Spore-Middleware-DefaultParams
requires:
  Class::MOP::Class: 0
  Moose: 0
  Net::HTTP::Spore::Meta::Method: 0
  Net::HTTP::Spore::Middleware: 0
version: 0.02
